name: Build ROS 2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push: 
    branches:
      - main

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@0.6.1
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: meldog_logger
